import os
import joblib
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def train_model(
    feature_csv: str,
    model_path: str,
    *,
    test_size: float = 0.2,
    random_state: int = 42,
    **rf_kwargs,
) -> dict:
    """Train a RandomForest classifier on the feature CSV.

    Parameters
    ----------
    feature_csv: str
        Path to the CSV file containing the feature DataFrame generated by Task 2.
    model_path: str
        Destination path where the trained model will be saved (joblib format).
    test_size: float, default 0.2
        Fraction of data to hold out for validation.
    random_state: int, default 42
        Random seed for reproducibility.
    **rf_kwargs:
        Additional keyword arguments forwarded to ``RandomForestClassifier``.

    Returns
    -------
    dict
        Dictionary with keys ``accuracy``, ``confusion_matrix`` (as a list of lists),
        and ``classification_report`` (text).
    """
    # Load features
    df = pd.read_csv(feature_csv)
    if "image_path" not in df.columns:
        raise ValueError("Feature CSV must contain an 'image_path' column.")

    # Expect a column named 'defect_type' containing the label
    if "defect_type" not in df.columns:
        raise ValueError("Feature CSV must contain a 'defect_type' column for training.")
    y = df["defect_type"]
    X = df.drop(columns=["image_path", "defect_type"])

    # Split into train / validation
    X_train, X_val, y_train, y_val = train_test_split(
        X, y, test_size=test_size, random_state=random_state, stratify=y
    )

    # Build the classifier (use defaults unless overridden)
    clf = RandomForestClassifier(**rf_kwargs)
    clf.fit(X_train, y_train)

    # Predict on validation set
    y_pred = clf.predict(X_val)
    acc = accuracy_score(y_val, y_pred)
    cm = confusion_matrix(y_val, y_pred).tolist()
    report = classification_report(y_val, y_pred)

    # Ensure the destination directory exists
    Path(model_path).parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(clf, model_path)

    return {
        "accuracy": acc,
        "confusion_matrix": cm,
        "classification_report": report,
    }
