import os
import shutil
import tempfile
from pathlib import Path
import json
import numpy as np
import pandas as pd
import pytest

# Task 1 generator to create a tiny synthetic dataset
from src.task1_synthetic.generator import SyntheticIndustrialGenerator

# Task 2 pipeline to extract features
from src.task2_opencv import batch_extract

# Task 3 functions
from src.task3_classifier import train_model, predict_defect

@pytest.fixture(scope="module")
def synthetic_dataset_dir():
    """Create a temporary directory with a tiny synthetic dataset (2 images per class)."""
    tmp_dir = Path(tempfile.mkdtemp())
    generator = SyntheticIndustrialGenerator()
    generator.generate_dataset(output_dir=tmp_dir, samples_per_class=2, seed=123)
    yield tmp_dir
    shutil.rmtree(tmp_dir, ignore_errors=True)

def build_features_csv(dataset_dir: Path, csv_path: Path) -> None:
    """Run Task 2 feature extraction and augment the DataFrame with the defect label.
    The resulting CSV will contain all feature columns plus a ``defect_type`` column.
    """
    # Collect image file paths
    image_paths = list(map(str, (dataset_dir / "images").glob("*.png")))
    # Extract features
    df: pd.DataFrame = batch_extract(image_paths)
    # Load metadata generated by the generator
    with open(dataset_dir / "metadata.json", "r", encoding="utf-8") as f:
        meta = json.load(f)
    # Add defect_type column based on filename
    defect_labels = []
    for img_path in df["image_path"]:
        filename = Path(img_path).name
        defect_labels.append(meta[filename]["defect_type"])
    df["defect_type"] = defect_labels
    # Write CSV
    df.to_csv(csv_path, index=False)

def test_train_model_creates_model_and_returns_metrics(synthetic_dataset_dir):
    tmp_dir = Path(tempfile.mkdtemp())
    csv_path = tmp_dir / "features.csv"
    model_path = tmp_dir / "rf_model.joblib"

    # Build CSV with features + label
    build_features_csv(synthetic_dataset_dir, csv_path)

    # Train the RandomForest model
    results = train_model(str(csv_path), str(model_path))

    # Basic assertions
    assert os.path.isfile(model_path), "Model file was not created"
    assert isinstance(results, dict)
    assert "accuracy" in results
    assert isinstance(results["accuracy"], float)
    assert 0.0 <= results["accuracy"] <= 1.0

    # Clean up
    shutil.rmtree(tmp_dir, ignore_errors=True)

def test_predict_defect_returns_correct_label(synthetic_dataset_dir):
    tmp_dir = Path(tempfile.mkdtemp())
    csv_path = tmp_dir / "features.csv"
    model_path = tmp_dir / "rf_model.joblib"

    build_features_csv(synthetic_dataset_dir, csv_path)
    train_model(str(csv_path), str(model_path))

    # Pick a random image from the dataset and its ground‑truth label
    image_path = next((synthetic_dataset_dir / "images").glob("*.png"))
    with open(synthetic_dataset_dir / "metadata.json", "r", encoding="utf-8") as f:
        meta = json.load(f)
    true_label = meta[image_path.name]["defect_type"]

    pred_label = predict_defect(str(image_path), str(model_path))

    # The prediction should be one of the known defect types and match the ground truth
    assert pred_label in {"normal", "scratch", "crack", "corrosion", "dimensional"}
    assert pred_label == true_label

    shutil.rmtree(tmp_dir, ignore_errors=True)
